name: 'Docker Setup'
description: 'Used to perform common setup steps for docker builds'
inputs:
  DOCKER_USERNAME:
    description: 'DOCKER_USERNAME'
    required: false
  DOCKER_PASSWORD:
    description: 'DOCKER_PASSWORD'
    required: false
runs:
  using: "composite"
  steps:
    # Configure credentials
    # It seems like this must be done before the setup-buildx-action in order to not mess up the config for buildx
    - uses: docker/login-action@v3
      if: "${{ inputs.DOCKER_USERNAME != '' }}"
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}
    # This step is required in order to use buildx provided by Docker. More on this here: https://github.com/docker/setup-buildx-action
    # and here: https://betterprogramming.pub/build-and-deploy-multi-architecture-graviton-container-images-for-spring-boot-microservices-f220d66cb3e3
    - name: Set up QEMU dependency
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64, amd64 # By default QEMU will create almost a dozen vm’s. Limit it to just the architectures we care about.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3