import json
import os
import unittest
from unittest import mock

from fastmcp import FastMCP

from . import AutoRefactor

class TestAutoRefactor(unittest.TestCase):
    def test_refactor(self):
        # Use mock data generated by running the CLI commands
        mock_data_files = {
          'parse-fns': 'code_health_auto_refactor/parse_fns.json',
          'review': 'code_health_auto_refactor/review_data.json'
        }

        def mock_run_local_tool(command: list, cwd: str = None):
            cli_command = command[1]
            with open(mock_data_files[cli_command], 'r') as file:
              return file.read()

        def mock_post_refactor(payload: dict) -> dict:
            payload['source-snippet'].pop('body')
            
            # Check that the payload for ACE looks like it should... 
            self.assertEqual({
              'api-version': 'v2',
              'source-snippet': {
                'file-type': 'cpp',
                'function-type': 'MemberFn'
              },
              'review': [
                {'category': 'Complex Method', 'start-line': 1}, 
                {'category': 'Complex Conditional', 'start-line': 13}
              ]
            }, payload)

            # ...and return a dummy response
            return {
              'code': 'public void start() {}',
              'metadata': {
              },
              'confidence': {
                'description': 'high-confidence',
              },
              'reasons': [
                {
                  'summary': 'The Large Method code smell remains, but the overall code health improves.'
                }
              ],
              'refactoring-properties': {
                'added-code-smells': [
                  'Large Method',
                  'Bumpy Road Ahead',
                  'Complex Method'
                ],
                'removed-code-smells': []
              },
              'reasons-with-details': [
                {
                  'summary': 'The Large Method code smell remains, but the overall code health improves.'
                }
              ]
          }

        self.instance = AutoRefactor(FastMCP('Test'), {
            'adapt_file_path_fn': lambda p: p,
            'post_refactor_fn': mock_post_refactor,
            'run_local_tool_fn': mock_run_local_tool,
        })

        expected = {
            'code': 'public void start() {}',
            'declarations': '',
            'confidence': 'high-confidence',
            'reasons': ['The Large Method code smell remains, but the overall code health improves.']
        }

        result = self.instance.code_health_auto_refactor('some-file.cpp', 'Document::moveObject')
      

        self.assertEqual(expected, json.loads(result))

