name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test-npm:
    runs-on: ubuntu-latest
    name: NPM Wrapper Unit Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
        working-directory: npm
      - name: Run npm unit tests with coverage
        run: npm run test:ci
        working-directory: npm
      - name: Upload npm coverage report
        uses: actions/upload-artifact@v4
        with:
          name: npm-coverage-report
          path: npm/coverage/cobertura-coverage.xml

  test-rust:
    runs-on: ubuntu-latest
    name: Rust Unit Tests + Coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install coverage tooling
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run Rust tests with cobertura coverage
        run: cargo llvm-cov --workspace --cobertura --output-path coverage.xml
      - name: Upload Rust coverage report
        uses: actions/upload-artifact@v4
        with:
          name: rust-coverage-report
          path: coverage.xml

  cs-coverage-check:
    runs-on: ubuntu-24.04
    needs: [test-npm, test-rust]
    if: always()
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch everything so that `cs-coverage check` can find merge-base
          fetch-depth: 0
      - name: download coverage
        uses: actions/download-artifact@v5
        with:
          path: coverage/
      - uses: ./.github/actions/check-coverage
        if: always()
        with:
          access-token: ${{ secrets.CODESCENE_CODE_COVERAGE_API_TOKEN }}
          project-url: "https://api.codescene.io/v2/projects/72556"
          # Include coverage files from all the artifacts (jobs)
          coverage-files: "**/*coverage.xml"
