//! Shared helpers for the `rules_config_*` tools.
//!
//! These tools wrap the `cs rules-config` CLI subcommands, which validate and
//! edit a Code Health rules file (`.codescene/code-health-rules.json`). All of
//! them are local, filesystem-only operations: no CodeScene API or license is
//! required.
//!
//! The helpers here centralize the two concerns every subcommand shares:
//! rejecting flag-like user input (option-injection defense) and choosing the
//! working directory the CLI runs in based on an optional `config_path`.

use std::path::{Path, PathBuf};

use crate::cli;
use crate::cli::CliRunner;
use crate::docker;
use crate::errors::CliError;

/// The `cs rules-config` subcommand to invoke.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Subcommand {
    Validate,
    ListThresholds,
    SetRule,
    SetThreshold,
}

impl Subcommand {
    fn as_arg(self) -> &'static str {
        match self {
            Subcommand::Validate => "validate",
            Subcommand::ListThresholds => "list-thresholds",
            Subcommand::SetRule => "set-rule",
            Subcommand::SetThreshold => "set-threshold",
        }
    }
}

/// A single `--name value` option pair supplied to the CLI.
#[derive(Debug)]
struct Opt {
    name: &'static str,
    value: String,
}

/// Builds the argument list and resolves the working directory for a
/// `cs rules-config` invocation, guarding every user-supplied value.
#[derive(Debug)]
pub(crate) struct Invocation {
    subcommand: Subcommand,
    opts: Vec<Opt>,
    config_path: Option<String>,
}

impl Invocation {
    pub(crate) fn new(subcommand: Subcommand) -> Self {
        Self {
            subcommand,
            opts: Vec::new(),
            config_path: None,
        }
    }

    /// Add a required string option, rejecting flag-like values.
    pub(crate) fn option(mut self, name: &'static str, value: &str) -> Result<Self, CliError> {
        reject_flag_like(value, name)?;
        self.opts.push(Opt {
            name,
            value: value.to_string(),
        });
        Ok(self)
    }

    /// Add an option whose value is generated by us (never flag-like), so it
    /// needs no injection check (e.g. a boolean or integer).
    pub(crate) fn trusted_option(mut self, name: &'static str, value: String) -> Self {
        self.opts.push(Opt { name, value });
        self
    }

    /// Add an optional selector/string option when present.
    pub(crate) fn maybe_option(
        self,
        name: &'static str,
        value: Option<&str>,
    ) -> Result<Self, CliError> {
        match value {
            Some(v) => self.option(name, v),
            None => Ok(self),
        }
    }

    /// Record an optional `--config-path`. An empty string is treated as
    /// "not provided" so callers can pass through defaults freely. The path is
    /// adapted for Docker so the CLI — which runs inside the container — and its
    /// working directory both reference a container-reachable location.
    pub(crate) fn config_path(mut self, path: Option<&str>) -> Result<Self, CliError> {
        let Some(path) = non_empty(path) else {
            return Ok(self);
        };
        require_absolute(path)?;
        reject_flag_like(path, "config_path")?;
        self.config_path = Some(docker::adapt_path_for_docker(Path::new(path)));
        Ok(self)
    }

    /// Run the CLI, returning its stdout on success.
    pub(crate) async fn run(self, cli_runner: &dyn CliRunner) -> Result<String, CliError> {
        let working_dir = self.working_dir();
        let args = self.build_args();
        let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
        cli_runner.run(&arg_refs, working_dir.as_deref()).await
    }

    fn build_args(&self) -> Vec<String> {
        let mut args = vec![
            "rules-config".to_string(),
            self.subcommand.as_arg().to_string(),
        ];
        for opt in &self.opts {
            args.push(opt.name.to_string());
            args.push(opt.value.clone());
        }
        if let Some(path) = &self.config_path {
            args.push("--config-path".to_string());
            args.push(path.clone());
        }
        args.push("--format".to_string());
        args.push("json".to_string());
        args
    }

    /// Choose the directory the CLI runs in. The CLI must run inside the user's
    /// repository so it can locate the default config and language rules. When a
    /// `config_path` is given, run from its git root (or its parent directory as
    /// a fallback); the path is already Docker-adapted, so this resolves to a
    /// container-side directory. Otherwise, inside Docker, fall back to the
    /// bind-mounted workspace; elsewhere let the CLI use the process's own
    /// working directory.
    fn working_dir(&self) -> Option<PathBuf> {
        match self.config_path.as_deref() {
            Some(path) => git_root_or_parent(Path::new(path)),
            None => docker::container_workspace_dir(),
        }
    }
}

/// Resolve the git root containing `path`, falling back to its parent dir.
fn git_root_or_parent(path: &Path) -> Option<PathBuf> {
    cli::find_git_root(path).or_else(|| path.parent().map(Path::to_path_buf))
}

fn non_empty(value: Option<&str>) -> Option<&str> {
    value.map(str::trim).filter(|v| !v.is_empty())
}

fn require_absolute(path: &str) -> Result<(), CliError> {
    if Path::new(path).is_absolute() {
        return Ok(());
    }
    Err(CliError::InvalidInput(format!(
        "config_path must be an absolute path: {path}"
    )))
}

/// Reject any user-supplied value that looks like a CLI flag, preventing
/// option-injection when passed as an argument to the `cs` CLI.
fn reject_flag_like(value: &str, param_name: &str) -> Result<(), CliError> {
    if value.trim().starts_with('-') {
        return Err(CliError::InvalidInput(format!(
            "{param_name} must not start with '-': {}",
            value.trim()
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn build(inv: Invocation) -> Vec<String> {
        inv.build_args()
    }

    #[test]
    fn validate_builds_minimal_args() {
        let args = build(Invocation::new(Subcommand::Validate));
        assert_eq!(args, vec!["rules-config", "validate", "--format", "json"]);
    }

    #[test]
    fn list_thresholds_includes_language() {
        let inv = Invocation::new(Subcommand::ListThresholds)
            .option("--language", "Python")
            .unwrap();
        let args = build(inv);
        assert_eq!(
            args,
            vec![
                "rules-config",
                "list-thresholds",
                "--language",
                "Python",
                "--format",
                "json"
            ]
        );
    }

    #[test]
    fn set_rule_includes_selector_and_config_path() {
        let inv = Invocation::new(Subcommand::SetRule)
            .option("--rule-name", "Complex Method")
            .unwrap()
            .trusted_option("--enabled", "false".to_string())
            .maybe_option("--matching-content-path", Some("**/*.js"))
            .unwrap()
            .config_path(Some("/repo/.codescene/code-health-rules.json"))
            .unwrap();
        let args = build(inv);
        assert_eq!(
            args,
            vec![
                "rules-config",
                "set-rule",
                "--rule-name",
                "Complex Method",
                "--enabled",
                "false",
                "--matching-content-path",
                "**/*.js",
                "--config-path",
                "/repo/.codescene/code-health-rules.json",
                "--format",
                "json"
            ]
        );
    }

    #[test]
    fn maybe_option_skips_when_absent() {
        let inv = Invocation::new(Subcommand::SetRule)
            .maybe_option("--matching-content-path", None)
            .unwrap();
        assert!(!build(inv).iter().any(|a| a == "--matching-content-path"));
    }

    #[test]
    fn config_path_empty_is_ignored() {
        let inv = Invocation::new(Subcommand::Validate)
            .config_path(Some("   "))
            .unwrap();
        assert!(!build(inv).iter().any(|a| a == "--config-path"));
    }

    #[test]
    fn config_path_requires_absolute() {
        let err = Invocation::new(Subcommand::Validate)
            .config_path(Some("relative/path.json"))
            .unwrap_err();
        assert!(err.to_string().contains("absolute path"));
    }

    #[test]
    fn option_rejects_flag_like_value() {
        let err = Invocation::new(Subcommand::SetRule)
            .option("--rule-name", "--sneaky")
            .unwrap_err();
        assert!(err.to_string().contains("must not start with '-'"));
    }

    #[test]
    fn config_path_rejects_flag_like_value() {
        let err = Invocation::new(Subcommand::Validate)
            .config_path(Some("-/etc/passwd"))
            .unwrap_err();
        // Absolute check runs first; a leading '-' is not absolute.
        assert!(err.to_string().contains("absolute path"));
    }

    #[test]
    fn working_dir_none_without_config_path() {
        assert!(Invocation::new(Subcommand::Validate)
            .working_dir()
            .is_none());
    }

    #[test]
    fn working_dir_falls_back_to_parent_dir() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path().join("code-health-rules.json");
        std::fs::write(&cfg, "{}").unwrap();
        let inv = Invocation::new(Subcommand::Validate)
            .config_path(Some(cfg.to_str().unwrap()))
            .unwrap();
        assert_eq!(inv.working_dir().unwrap(), dir.path());
    }

    #[test]
    fn working_dir_prefers_git_root() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join(".git")).unwrap();
        let nested = dir.path().join(".codescene");
        std::fs::create_dir_all(&nested).unwrap();
        let cfg = nested.join("code-health-rules.json");
        std::fs::write(&cfg, "{}").unwrap();
        let inv = Invocation::new(Subcommand::Validate)
            .config_path(Some(cfg.to_str().unwrap()))
            .unwrap();
        assert_eq!(inv.working_dir().unwrap(), dir.path());
    }

    #[test]
    fn config_path_used_verbatim_outside_docker() {
        // Outside Docker, adapt_path_for_docker is a no-op, so the CLI arg
        // matches the absolute path the caller provided.
        let path = if cfg!(windows) {
            r"C:\repo\.codescene\code-health-rules.json"
        } else {
            "/repo/.codescene/code-health-rules.json"
        };
        let inv = Invocation::new(Subcommand::Validate)
            .config_path(Some(path))
            .unwrap();
        let args = build(inv);
        let idx = args.iter().position(|a| a == "--config-path").unwrap();
        assert_eq!(args[idx + 1], path);
    }

    #[test]
    fn subcommand_as_arg_maps_correctly() {
        assert_eq!(Subcommand::Validate.as_arg(), "validate");
        assert_eq!(Subcommand::ListThresholds.as_arg(), "list-thresholds");
        assert_eq!(Subcommand::SetRule.as_arg(), "set-rule");
        assert_eq!(Subcommand::SetThreshold.as_arg(), "set-threshold");
    }
}
